### ISSUE TITLE
Xiaomi-App File Manager: deutsche Übersetzung für "sort direction"

### ISSUE THREAD

**Issue by fbfrank** [berlinux2016/HyperOS-1.0#10]
- **HyperOS version:** 1.0.36.0
- **Device name:** Xiaomi 14

**Screenshot/Description:** Xiaomi-App File Manager: deutsche Übersetzung für "sort direction" ist hier mit "weiter" und "umgekehrt" angeben, unabhängig von "Filter-Typ"

![Screenshot_2024-04-30-10-06-11-088_com android fileexplorer](https://github.com/berlinux2016/HyperOS-1.0/assets/46959669/211fab5d-15a1-4be3-a87c-b4f74fa70439)

**Comment by MeiGuddet** [comment]
Ok, guck ich mir morgen an.
