### ISSUE TITLE
Fehlende Übersetzung 

### ISSUE THREAD

**Issue by Titanium2424** [berlinux2016/HyperOS-1.0#11]
HyperOS 1.0.24.5.13.Dev
Xiaomi 14 Pro 
Einstellungen/Akku/
Fehlende Übersetzung für Charging Options
![Screenshot_2024-05-20-22-12-44-361_com miui securitycenter](https://github.com/berlinux2016/HyperOS-1.0/assets/170365985/5be76fee-c32d-4ee4-bab9-65901b67b71b)

**Comment by MeiGuddet** [comment]
Das hab ich am So 19.05. übersetzt, ist dann in der nächsten ROM drin.
