### ISSUE TITLE
Galerie: Move und Copy 

### ISSUE THREAD

**Issue by darki15** [berlinux2016/HyperOS-1.0#12]
Hi,

Galerie -> Mehr -> Zum Album hinzufügen 

Dort erscheinen nach Auswahl des Albums "Move" und "Copy".

Ich nutze die aktuellste weekly ROM.

VG

**Comment by MeiGuddet** [comment]
Das müsste der array hier sein:

>      <string-array name="menu_copy_or_move">
>         <item>Move</item>
>         <item>Copy</item>
>         <item>@string/cancel</item>
>      </string-array>
Der darf ggf. nicht übersetzt werden.

@IgorEisberg @ingbrzy Is this array allowed to be translated? I'm referring to the 2 items "Move" and "Copy".

**Comment by MeiGuddet** [comment]
Ich probier's jetzt mal und mache den array rein. Mal sehen, was dann passiert.

**Comment by MeiGuddet** [comment]
OK. Wurde gelöscht.
Abgeändert und nochmal rein gemacht. Sollte jetzt passen.
