### ISSUE TITLE
Wrong translation - Änderungsvorschläge

### ISSUE THREAD

**Issue by ezgerazer** [berlinux2016/HyperOS-1.0#13]
HyperOS Version: 1.0.24.6.24.DEV
Device; DITING - Xiaomi 12T Pro
-------
2nd Device
HyperOS Version: 816.0.5.0.TJBCNXM
Device: UMI - Xiaomi Mi 10

Guten Morgen, Tag, Abend oder wann auch immer man das hier sieht. :)

Ich bin mit einigen Übersetzungen in der Xiaomi.eu ROM unzufrieden (edit nach comment von MeiGuddet: unzufrieden ist hier der falsche Begriff, die Übersetzung kling an manchen Stellen etwas komisch), weswegen ich hier paar verbesserungsvorschläge biete.
Mir ist bewusst, dass ihr das in eurer Freizeit macht aber Fehler sind eher, najaa.. :)

Dabei versteht sich das Format so:
# Objekt:
aktuell -> mein Vorschlag

# Taschenlampe:
- Blitzlicht -> Taschenlampe

Was soll Blitzlicht denn sein? :)

# Energiesparmodus:
- Stromsparen -> Energiesparmodus
- Ultra-Stromsparen -> Ultra-Energiesparmodus

# Werkseinstellungen:
- Werksreset -> Werkseinstellungen
 Im Menü von "Werksreset"
- Folgende Elemente löschen -> Folgende Elemente werden gelöscht

Ich bedanke mich für das durchlesen meiner Anfrage. Hoffentlich ist die etwas verständlich :)

**Comment by MeiGuddet** [comment]
Vorab eine Klarstellung: Nur weil du mit einigen Übersetzungnen unzufrieden bist, sind dass noch lange keine Fehler. Deinen Post finde ich daher eher najaa.. :)

Taschenlampe: Nicht immer ist die Taschenlampe gemeint. Wird nur dann auch so übersetzt, wenn das im vorhandenen string ersichtlich ist. (Du weißt nicht, was ein Blitzlicht ist? Oha.)
Stromsparen und Ultra-Stromsparen: Bleiben so, kurz und verständlich.
Werksreset: Kann man nicht pauschal übersetzen mit "Werkseinstellungen". Der Begriff bedeutet "auf Werkseinstellungen zurücksetzen" und wird dann benutzt, wenn es passend ist. Ansonsten kurz Werksreset.
Folgende Elemente löschen: Bleibt auch so bzw. kommt auf den Zusammenhang an. Keine pauschale Übersetzung mit "Folgende Elemente werden gelöscht".

**Comment by ezgerazer** [comment]
Hey MeiGuddet, ich wollte mich an dieser Stelle entschuldigen, 
der Post sollte nicht arrogant rüber kommen.
Ich habe die wohl die falschen Begriffe verwendet. Natürlich sind das keine Fehler, sie klingen nur etwas ungewöhnlich für mich.

Zum Punkt Taschenlampe: Ja, ich weiß was ein Blitzlicht ist aber ich denke, dass dieser Begriff eher nicht in ein Betriebssystem passt. In der HyperOS 1.0.3.0. von Xiaomi.eu heißt die Taschenlampe schlichthin "Lampe".
![lampe](https://github.com/berlinux2016/HyperOS-1.0/assets/82302097/f58b1f3a-b34f-4f7d-a46b-d435db828146)
Dort heißt die Option "Werksreset" auch "Werkseinstellungen"
![werkseinstellungen](https://github.com/berlinux2016/HyperOS-1.0/assets/82302097/c6fb27f9-acd8-492e-84b0-3084876d4ab2)

Gut, ich denke mal. dass ich muss ich einfach mal umgewöhnen.
Tut mir leid, dass ich deine Zeit verschwendet hatte. Dennoch vielen Dank, dass du dich gemeldet hast!

**Comment by MeiGuddet** [comment]
Ich habe nicht gesagt, dass du meine Zeit verschwendet hast, sondern ich habe nur was klargestellt.
Was genau willst du mit diesen Screenshots sagen?
In der Benachrichtigungsleiste ist die Taschenlampe aus Platzgründen bewusst mit "Lampe" übersetzt (dein 1. Screenshot), nicht mit "Blitzlicht", passt also. "Blitzlicht" wird verwendet, wenn es um die Kamera geht.
In deinem 2. Screenshot steht im Englischen "Factory reset", das ist jetzt mit "Werksreset" übersetzt, passt meiner Ansicht  nach besser, ist ein allgemein gebräuchlicher eingdeutschter Begriff.

**Comment by ezgerazer** [comment]
Moin,
das mit Lampe im Kontrollzentrum hatte ich ursprünglich auch gemeint, tut mir leid, dass ich das nicht genauer erläutert hatte.
Die "Lampe" im Kontrollzentrum heißt in den neueren Version Blitzlicht, etwas komisch. :D

Schönen Tag noch!

**Comment by MeiGuddet** [comment]
> Die "Lampe" im Kontrollzentrum heißt in den neueren Versionen Blitzlicht, etwas komisch.

Merkwürdig. `<string name="status_bar_toggle_torch">Lampe</string>`

**Comment by ezgerazer** [comment]
![grafik](https://github.com/user-attachments/assets/95eb1220-602a-49aa-80f6-9c434535c101)
Das ist ja lustig :D

**Comment by MeiGuddet** [comment]
Anhand des Screenshots habe ich jetzt nochmal gesucht ("Auto-Helligkeit") und die hoffentlich passenden strings für die Lampe gefunden. Sind anscheinend jetzt andere strings für die Tasten da. Übersetzung ist aber erst bei der nächsten ROM-Veröffentlichung drin.

**Comment by ezgerazer** [comment]
Alles klar, vielen Dank mein lieber! :)
