### ISSUE TITLE
Translation policy changes

### ISSUE THREAD

**Issue by kacskrz** [berlinux2016/HyperOS-1.0#14]
Hello,

We announced changes regarding Xiaomi.eu translation policy: https://xiaomi.eu/community/threads/change-in-xiaomi-eu-translation-policy-important-announcement-for-translators.73817/

It's very recommended to adjust to these changes, as it will make your translation, in most cases, much smaller.

Regards!
Kacper Skrzypek
Polish Xiaomi.eu translator

**Comment by MeiGuddet** [comment]
Yes, I will adjust the German translation to these changes, but it will take up some time.

**Comment by MeiGuddet** [comment]
Adjustment is ongoing.
