### ISSUE TITLE
WLAN-Anrufe

### ISSUE THREAD

**Issue by darki15** [berlinux2016/HyperOS-1.0#15]
Hi,

Mobilfunknetze - SIM-Einstellungen - WLAN-Anrufe

Aktiviert man dies, ist im Hinweis-Popup über Notrufe nach dem Punkt des ersten Satzes ein einzelnes "n".

Stable und Beta ROM seit geraumer Zeit.

VG darki

**Comment by Henry2o1o** [comment]
Erledigt
