### ISSUE TITLE
Datumsformate Sperrbildschirm

### ISSUE THREAD

**Issue by darki15** [berlinux2016/HyperOS-1.0#3]
Hallo,

beim Bearbeiten des Sperrbildschirms sind alle Datumsformate gleich (18/11 statt z. B. 18.11.2023).

Grüße

**Comment by berlinux2016** [comment]
Der Fehler kommt aus der China ROM HyperOS.

**Comment by darki15** [comment]
Ingbrzy sagte im HyperOS Thread, dass es von der Übersetzung kommt:
https://xiaomi.eu/community/threads/23-11-8-13-16.70548/page-5#post-706101

Irrt er sich?

**Comment by berlinux2016** [comment]
Einfach zu testen. Sprache umstellen auf FR oder ES usw. Wird dann immer noch alles wie in DE angezeigt (editieren Sperrbildschirm - lange drücken)

**Comment by darki15** [comment]
Sprache ändern brachte tatsächlich nicht viel. Aber ich schau in der nächsten ROM nochmal. Danke erstmal!

**Comment by Henry2o1o** [comment]
Lag vermutlich an den fehlenden Strings 🤷‍♂️

**Comment by darki15** [comment]
Update auf 23.11.27 durchgeführt. Problem noch vorhanden.

**Comment by MeiGuddet** [comment]
Verstehe ich nicht. Dann gehe ich wieder mal auf die Suche.

**Comment by MeiGuddet** [comment]
Ich hatte einen Verdacht, den hab ich reingenommen. Wird dann aber erst bei der nächsten Version sichtbar.
Kann es auch selbst nicht testen, da ich aktuell kein HyperOS habe.

**Comment by darki15** [comment]
Danke. Ich gebe dann nochmal Feedback.

**Comment by darki15** [comment]
Ich habe mir die Einstellungen für den Sperrbildschirm nochmal genauer angesehen. Das Datum wird "korrekt" angezeigt, wenn man einen Sperrbildschirm wählt, bei dem das Datum nicht bearbeitet werden kann. Wählt man einen Sperrbildschirm, bei dem das Bearbeiten möglich ist, gibt's viele Auswahlmöglichkeiten, die alle ähnlich sind und nicht dem deutschen format entsprechen.
![Screenshot_2023-12-02-22-38-31-917_com miui aod](https://github.com/berlinux2016/HyperOS-1.0/assets/20324125/969bdcd9-5725-4b09-b442-39be70d9bff8)
![Screenshot_2023-12-02-22-39-05-672_com miui aod](https://github.com/berlinux2016/HyperOS-1.0/assets/20324125/576c1d5e-b3f6-4d5c-99e6-b7c7c064b977)

**Comment by MeiGuddet** [comment]
Das Problem hier ist: Diese strings beziehen sich auf den traditionellen chinesischen Kalender. Hier kann man nicht vorgeben, so zu schreiben: 02.12. (
Die chinesischen Schriftzeichen bedeuten hier: 2. Tag des (Mond-)Monats. 
Das kann man also nicht auf das Deutsche anwenden. Die normalen strings für das Format werden hier nicht gezogen.
Kannst du mal Screenshots posten, wie das in Englisch aussieht?

**Comment by darki15** [comment]
![Screenshot_2023-12-03-12-04-03-282_com miui aod](https://github.com/berlinux2016/HyperOS-1.0/assets/20324125/38235ebe-6da3-4ae2-980f-779ffacd3df7)

**Comment by MeiGuddet** [comment]
Das muss ich mir nochmal genauer ansehen.

**Comment by MeiGuddet** [comment]
Hab nochmal ein paar strings überarbeitet, kann aber für nix garantieren.

**Comment by darki15** [comment]
Es ist besser geworden.
![Screenshot_2023-12-10-10-00-45-851_com miui aod](https://github.com/berlinux2016/HyperOS-1.0/assets/20324125/46a39e73-d00e-48fa-8107-096613b9f214)

**Comment by MeiGuddet** [comment]
Ok, aber mehr Möglichkeiten sehe ich da nicht.

**Comment by darki15** [comment]
Ist ja schon deutlich besser so :) Danke
