### ISSUE TITLE
Number of notification icons shown

### ISSUE THREAD

**Issue by darki15** [berlinux2016/HyperOS-1.0#4]
Hallo,

mit der neuen HyperOS Beta 24.1.8 ist ein Punkt aus dem Changelog in der ROM noch nicht übersetzt.

"Number of notification icons shown"

Vielleicht habt ihr das schon auf dem Zettel, aber sicher ist sicher 😁

Viele Grüße

**Comment by MeiGuddet** [comment]
Hab ich gestern nachmittag übersetzt, hat es anscheinend noch nicht in die ROM geschafft.
