### ISSUE TITLE
Intelligente Gerätesteuerung: None

### ISSUE THREAD

**Issue by darki15** [berlinux2016/HyperOS-1.0#5]
Hi,

folgendes Wort wurde noch nicht übersetzt.
Benachrichtigungen und Statusleiste 
Intelligente Gerätesteuerung
**None**

Viele Grüße

**Comment by MeiGuddet** [comment]
Ich habe alle neuen strings, die mit der ROM 24.1.8/11 gekommen sind, gestern übersetzt.
Aber alle Übersetzungen nach 12 Uhr mittags sind anscheinend noch nicht drin.
Und das Wort "None" kommt 164 mal vor, so einfach lässt sich das nicht finden :grinning:

**Comment by darki15** [comment]
Ok 😀 Das ist mir allerdings schon in 2 oder 3 ROMs zuvor aufgefallen, also nicht erst mit der 24.1.8.

**Comment by MeiGuddet** [comment]
Na dann gehe ich mal auf die Suche.

**Comment by MeiGuddet** [comment]
@darki15 Ist der Fehler jetzt eigentlich behoben?

**Comment by darki15** [comment]
@MeiGuddet Leider nein

**Comment by MeiGuddet** [comment]
Es gibt da einen Array:  `<string-array name="smart_device_control_entries">`
Und der darf nicht übersetzt werden. Sieht so aus, als ist es genau der :grin:
