### ISSUE TITLE
"Schneiden" statt "Ausschneiden" bei Texten

### ISSUE THREAD

**Issue by Jonas225** [berlinux2016/HyperOS-1.0#6]
- **HyperOS version:** 1.0
- **Device name:** Xiaomi 12 (Cupid)

**Screenshot/Description:**
Bei Copy & Paste von Texten wurde "Ausschneiden" mit "Schneiden" übersetzt.

Viele Grüße

**Comment by MeiGuddet** [comment]
Ok. Ist geändert.
