### ISSUE TITLE
2g only translation missing 

### ISSUE THREAD

**Issue by BensaTV** [berlinux2016/HyperOS-1.0#7]
- **HyperOS version:** 1.0.8.0.ULQMIXM
- **Device name:** Xiaomi 12T

**Screenshot/Description:**

![IMG_20240312_130809](https://github.com/berlinux2016/HyperOS-1.0/assets/40702755/4a7c3881-761e-41b4-9420-95bf94213917)

**Comment by MeiGuddet** [comment]
Erledigt.
