### ISSUE TITLE
Wrong translation in MIUI 14 / HyperOS

### ISSUE THREAD

**Issue by ezgerazer** [berlinux2016/HyperOS-1.0#8]
- **HyperOS version:** 1.0.24.3.18.DEV
- **Device name:** Xiaomi (Diting) 12T Pro

**Screenshot/Description:**

// GERMAN

1.
![roaming](https://github.com/berlinux2016/HyperOS-1.0/assets/82302097/7af45631-3446-4c98-b347-cfbe8d137964)
Die Übersetzung von Internationalen Roaming unter Mobilfunknetze > Datenroaming ist falsch. 
Dort steht anstelle von **Internatioles Roaming** - **Nationales** Roaming, was schließlich falsch ist.
(Same for english, it's international roaming and NOT national.)

2.
![gps2](https://github.com/berlinux2016/HyperOS-1.0/assets/82302097/3bb28cdd-fabd-4882-8cf9-cebbc726a942)
![gps1](https://github.com/berlinux2016/HyperOS-1.0/assets/82302097/87872f87-00c3-4c05-a3e0-f3068d7e1992)
Ein weiter Punkt ist, dass unter Standortzugriff egal ob deaktiviert oder aktiviert, dort AUSSCHALTEN steht.. oder wie ist das hier gemeint?

// ENGLISH

The translation of International roaming under Mobile networks > Data roaming is incorrect. 
Instead of **International roaming**, it says **National** roaming, which is wrong.
(Same for english, it's international roaming and NOT national.)

2.

Another point is that under location access, regardless of whether it is deactivated or activated, it says TURN OFF... or how is that meant here?

this is my first github message, pls don't be harsh :)

**Comment by MeiGuddet** [comment]
1. Der string heißt: `<string name="domestic_roaming_setting">National roaming</string>` Den haben, so wie ich das bis jetzt gesehen habe, alle Übersetzer mit 'Nationales Roaming' übersetzt (s. auch 'domestic'). Bin mir jetzt nicht sicher, ob der Schalter wirklich für das internationale Roaming ist, aber in der Global ROM steht an der Stelle 'Internationales Roaming'. Also hab ich es jetzt geändert.
2. Die beiden strings heißen: `<string name="assisted_gps_disabled">Use server to assist GPS (uncheck to improve GPS performance)</string>` und `<string name="assisted_gps_enabled">Use server to assist GPS (uncheck to reduce network usage)</string>`. Die direkte Übersetzung aus dem Chinesischen ist auch nicht hilfreich: bei _disabled 'Server zur Unterstützung von GPS verwenden (Nicht markieren verbessert die GPS-Leistung)' und bei _enabled 'Server zur Unterstützung von GPS verwenden (Nicht markieren reduziert die Netznutzung)'. Kann dir also nicht sagen, was genau das bedeuten soll.

**Comment by ezgerazer** [comment]
Hey nochmal zum ersten Punkt: 
Nationales Roaming würde wohl eher weniger Sinn ergeben. Ich hatte versucht, nationales Roaming in Deutschland zu verwenden, was (leider) nicht möglich :(. Wie du schon erwähnt hast, in der Global ROM steht dort an der stelle Internationales Roaming.

Zum zweiten Punkt:
<string name="assisted_gps_disabled">Use server to assist GPS (**uncheck** to improve GPS performance)</string>
Denke mal hier wäre Einschalten gut, da man ja den Switch "einschaltet" (Ich weiß nicht, wie ich's erklären soll).

Ansonsten, vielen Dank, dass du dir das du Herzen genommen hast!
