### ISSUE TITLE
Auf Sperrbildschirm angezeigte Elemente nach Runterwischen

### ISSUE THREAD

**Issue by darki15** [berlinux2016/HyperOS-1.0#9]
"Benachrichtigen & Statusleiste"
Hier der Punkt
"Auf Sperrbildschirm angezeigte Elemente nach Runterwischen"

Runterwischen sollte zu Herunterwischen geändert werden, da sonst umgangssprachlich.

VG

**Comment by Henry2o1o** [comment]
Anfangs hieß das noch "Nach oben wischen" und "Nach unten wischen" 🤷‍♂️

**Comment by MeiGuddet** [comment]
Erledigt.
